# Generated by Django 5.0.4 on 2024-04-18 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(max_length=200)),
                ("author", models.TextField(max_length=200)),
                ("year", models.TextField(max_length=200)),
                ("rating", models.TextField(max_length=200)),
                ("description", models.TextField(max_length=200)),
            ],
        ),
    ]
